apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jtxyl02dg-java-springboot
  janus-idp.io/tekton: jtxyl02dg-java-springboot
  backstage.io/kubernetes-id: jtxyl02dg-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jtxyl02dg-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
